version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: acdc_user
      POSTGRES_PASSWORD: acdc_password
      POSTGRES_DB: acdc_database
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-collector-container
    volumes:
      - ./output:/var/log/app/output/
    ports:
      - "8008:8008"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
