version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: acdc_user
      POSTGRES_PASSWORD: acdc_password
      POSTGRES_DB: acdc_database
    networks:
      - app-network
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "acdc_database", "-U", "acdc_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-collector-container
    volumes:
      - ./output:/var/log/app/output/
    ports:
      - "8008:8008"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
