fraulent_offers = [
    {
        "clasfieds_id": 750272695,
        "title": "Seat Alhambra Super Stan / NAVI / DVD / Polski Salon / 1.4 tsi 150 koni",
        "description": "WSZELKIE INFORMACJE POD NUMEREM <br /> <br /> Seat Alhambra 1.4 tsi 150 koni <br /> <br /> samochod w super stanie <br /> <br /> zawieszenie , silnik - pracuja idealnie , jezdzi sie jak fabrycznie nowym samochodem <br /> <br /> wnetrze zadbane pedantycznie , schludne , poszanowane <br /> <br /> wizualnie prezentuje sie przepieknie <br /> <br /> silnik 1.4 TSI ecomotive o mocy 150 koni polaczony z manualna skrzynia 6 biegowa daje rewelacyjne osiagi oraz niskie spalanie <br /> <br /> silnik nie ma problemu z pobieraniem oleju , jest tez swiezo po serwisie olejowym , serwisie klimatyzacji , wymieniony rozrzad , cewki oraz swiece <br /> <br /> samochod gotowy do uzytkowania bez wkladu finansowego <br /> <br /> Seat pochodzi z Polskiego salonu , posiada komplet dokumentów oraz komplet kluczy <br /> <br /> dodatkowo dokladam kola zimowe z prawie nowymi oponami na felgach aluminiowych <br /> <br /> polecam",
        "price": 35000,
        "milage": 186000,
        "model": "Alhambra",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "VSSZZZ7NZBV510542",
    },
    {
        "clasfieds_id": 776180845,
        "title": "Jeep Grand Cherokee !Stan idealny, przegląd 13.03.2025! ZAMIENIĘ",
        "description": "Dzień dobry,<br /> Do sprzedania Jeep Grand Cherokee. Jestem właścicielem samochodu blisko trzy lata. Idealna jednostka pod instalację gazową. Przy spalaniu ok. 20 litrów gazu przejazd 100 km to ok. 60 zł. Jak na tak potężny silnik, nie jest to wysoki koszt. Bezkolizyjny stan, nie uczestniczył w żadnym zdarzeniu drogowym. Niski przebieg wynika z okazjonalnego korzystania - wycieczki, weekendowe wyjazdy. Brązowy kolor skórzanej tapicerki nadaje wnętrzu oryginalny wygląd. Auto jest bardzo utrzymane. Świeżo po przeglądzie technicznym, następne badanie dopiero 13.03.2025 r.<br /> Samochód posiada m.in.:<br /> - wentylowane tarcze hamulcowe,<br /> - skórzane, wentylowane i grzane fotele przednie,<br /> - skórzane grzane fotele tylne,<br /> - podgrzewaną kierownicę,<br /> - nagłośnienie Harman Kardon,<br /> - możliwość uruchomienia auta zdalnie pilotem,<br /> - panoramiczny dach,<br /> - hak.<br /> Klimatyzacja po serwisie. Zapraszam do oglądania.",
        "price": 178000,
        "milage": 23057,
        "model": "Grand Cherokee",
        "condition": "Nieuszkodzony",
        "country_origin": "Stany Zjednoczone",
        "vin": "1C4RJFDJ0GC458317",
    },
    {
        "clasfieds_id": 799371168,
        "title": "Nissan Leaf N-Connecta 40kWh*Serwisowany w ASO*Na gwarancji fabrycznej*Idealna",
        "description": "Przed przyjazdem proszę o kontakt:<br /> Pomorski Krzysztof<br /> ☎  ☎<br /> <br /> 2018 Nissan Leaf N-Connecta 40kWh + 148KM silnik elektryczny<br /> <br /> ☑ Produkcja auta: 2018r. Pierwsza rejestracja: 05,04,2018r.<br /> ☑ Auto przygotowane do rejestracji,- klient dostaje komplet dokumentów niezbędnych do zarejestrowania auta na terytorium PL w cenie auta.<br /> ☑ Posiadamy dokumentację pochodzeniową włącznie ze zdjęciami. Auto z przejrzystą historią pochodzenia.<br /> ☑ Auto serwisowane na bieżąco w ASO NISSAN,- ostatni serwis wykonany 27,10,2022r. przy przebiegu: 73,755km.<br /> ☑ Dzięki regularnym wizytom w serwisie ASO auto wciąż posiada gwarancję fabryczną W TYM GWARANCJĘ NA AKUMULATOR!<br /> (Gwarancja na cały samochód do 24.10.2023 lub przebieg 103700 km. plus assistans holowania 27.10.2023 , za rok możliwość przedłużenia.<br /> Gwarancja na akumulator ważna do kwietnia 2026r. lub do przebiegu: 160tys. km.)<br /> ☑ Auto w najbogatszej wersji wyposażenia N-Connecta.<br /> ☑ Idealny stan techniczny i wizualny.<br /> <br /> Przed przyjazdem proszę o kontakt:<br /> Pomorski Krzysztof<br /> ☎  ☎<br /> <br /> WYPOSAŻENIE:<br /> - dostęp bez kluczykowy<br /> - pół-skórzana tapicerka<br /> - podgrzewane fotele przednie<br /> - podgrzewana tylna kanapa<br /> - podgrzewana kierownica<br /> - klimatyzacja automatyczna 2 strefowa<br /> - skórzana kierownica wielofunkcyjna z regulacją w 2 płaszczyznach<br /> - elektrycznie sterowane szyby x4<br /> - elektrycznie sterowane, składane i podgrzewane lusterka zewnętrzne<br /> - nawigacja z mapą PL i EU<br /> - Bluetooth<br /> - system kamer 360'<br /> - kamera cofania z wizualizacją trajektorii cofania<br /> - czujniki parkowania przód i tył<br /> - asystent parkowania<br /> - adaptacyjne przednie reflektory w technologii FULL LED<br /> - tempomat<br /> - asystent pasa ruchu<br /> - foto chromatyczne lusterko wsteczne<br /> - tryb jazdy ekonomicznej ECO<br /> - E-pedal<br /> - fabrycznie przyciemniane szyby z filtrem UV<br /> - mocowania fotelików dziecięcych Isofix<br /> - 8 poduszek powietrznych<br /> - ABS, ESP<br /> - immobilizer<br /> - autoalarm<br /> - aluminiowe felgi<br /> <br /> Przed przyjazdem proszę o kontakt:<br /> Pomorski Krzysztof<br /> ☎  ☎<br /> <br /> Na miejscu możliwość odbycia jazdy próbnej, wgląd w dokumentację samochodu,<br /> pomiar czujnikiem lakieru, rozmowa z osobą pomocną w finansowaniu zakupu.<br /> <br /> Prosimy o wcześniejszy kontakt przed przyjazdem w celu potwierdzenia dostępności auta.<br /> <br /> Oferujemy usługę dostarczenia auta do klienta.<br /> <br /> Możliwość zostawienia auta w rozliczeniu.<br /> <br /> Kupujący zwolniony z podatku PCC (2% wartości).",
        "price": 69900,
        "milage": 74651,
        "model": "Pozostałe Nissan",
        "condition": "Nieuszkodzony",
        "country_origin": "Dania",
        "vin": "SJNFAAZE1U0011631",
    },
    {
        "clasfieds_id": 808237164,
        "title": "Seat Ateca Sprzedam Seata Atece naped 4x4 automat boogata wersja.",
        "description": "Sprzedam  auto marki Seat Ateca.Rocznik 2017, automat w bardzo bogatej wersji excellence black edition.Auto w 100% sprawne , bardzo zadbane z malym oryginalnym przebiegiem 84000 km. Zarejestrowane w kraju.Więcej informacji udzielę tel.",
        "price": 84900,
        "milage": 84000,
        "model": "Pozostałe Seat",
        "condition": "Nieuszkodzony",
        "country_origin": "Dania",
        "vin": "VSSZZZ5FZJ6518800",
    },
    {
        "clasfieds_id": 812355233,
        "title": "Honda Civic TypeR GT 310KM",
        "description": "Honda Civic TypeR silnik 2.0T i VTEC o mocy 310 KM, manualna skrzynia biegów,<br /> <br /> wersja wyposażenia GT<br /> <br /> Auto w stanie bardzo dobrym, doposażony, nie wymaga wkładu finansowego.<br /> <br /> KONTAKT:<br />  ARTUR<br /> <br /> AUTORYZOWANY DEALER HONDA WYSZOMIRSKI W SIEDLCACH<br /> <br /> Informacje umieszczone na stronie internetowej służą jedynie celom informacyjnym i nie stanowią oferty w rozumieniu przepisów Kodeksu Cywilnego oraz opisu towaru ani zapewnienia w rozumieniu art. 4 Ustawy z dnia 27 lipca 2002 roku o szczególnych warunkach sprzedaży konsumenckiej.<br /> <br /> Indywidualne uzgodnienie właściwości i specyfikacji pojazdu następuje w umowie sprzedaży.",
        "price": 109900,
        "milage": 67800,
        "model": "Civic",
        "condition": "Nieuszkodzony",
        "country_origin": "Niemcy",
        "vin": "SHHFK2790FU702443",
    },
    {
        "clasfieds_id": 823023618,
        "title": "Jeep Grand Cherokee Jeep Grand Cherokee Gr 3.6 V6 Overland",
        "description": "Witam, mam do sprzedania samochód marki Jeep Grand Cherokee:<br /> <br /> - Bardzo niski przebieg 39k <br /> - rok produkcji: 2018<br /> - nowa instalacja LPG<br /> - silnik: 3.6 VVT <br /> - skrzynia biegów: automatyczna , 8-śmio biegowa,<br /> - Opłacony<br /> - zarejestrowany<br /> nr vin: 1C4RJFBG2JC322432<br /> <br /> Więcej informacji pod numerem:<br /> - <br /> <br /> Możliwy transport !!!<br /> <br /> Godziny otwarcia:<br /> pn. - pt. 8-16,<br /> sob. możliwa po wcześniejszym kontakcie telefonicznym<br /> <br /> email. przyczepy25wp.pl",
        "price": 123000,
        "milage": 39198,
        "model": "Grand Cherokee",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "1C4RJFBG2JC322432",
    },
    {
        "clasfieds_id": 825055838,
        "title": "Suzuki Swift Suzuki Swift Sport",
        "description": 'Oferta autoryzowanego dealera samochodów nowych DODGE, RAM i Suzuki .<br /> <br /> Swift Sport <br /> -Samochód na bieżąco serwisowany w ASO Suzuki<br /> -Świetny stan techniczny <br /> -Sportowy zderzak przedni<br /> -Zderzak tylny z nakładką w kształcie dyfuzora aerodynamicznego<br /> -Spojlery progowe<br /> -Spojler dachowy<br /> -Podwójna końcówka układu wydechowego<br /> -Czarne słupki nadwozia<br /> -Reflektory LED Hi/Low<br /> -Przyciemniane szyby w tylnej części nadwozia<br /> -Elektrycznie regulowane, podgrzewane i składane lusterka zewnętrzne<br /> -Sportowe fotele przednie <br /> -Pakiet Zimowy (podgrzewane fotele przednie + nawiew na nogi pasażerów z tyłu<br /> -Interaktywny system multimedialny z ekranem dotykowym 7"<br /> -Bluetooth® z zestawem głośnomówiącym<br /> -Kamera cofania <br /> -tempomat<br /> <br /> Dokumentacja zdjęciowa uszkodzeń pojazdu - pokrywa bagażnika , zderzak ,lampa tył do wglądu , samochód naprawiony w naszym ASO <br /> <br /> Polecam',
        "price": 72000,
        "milage": 60600,
        "model": "Swift",
        "condition": "Nieuszkodzony",
        "country_origin": "Niemcy",
        "vin": "JSAAZC33S00113378",
    },
    {
        "clasfieds_id": 826513938,
        "title": "Mitsubishi Colt 1,3 Pb + Lpg ekonomiczny spalanie od 5 l / 100 km klima elektryka",
        "description": "1,3 Pb   + instalacja Gazowa<br /> <br /> atest  LPG   - do 2030<br /> <br /> moc silnika 95 KM<br /> <br /> małe spalanie od 5 l  gazu   / 100 km przy ekonomicznej jeżdzie<br /> <br /> instalacja sekwencyjna LPG  <br /> <br /> nadwozie w ładnym stanie<br /> <br /> środek ładny<br /> <br /> kolor szary metalik <br /> <br /> klimatyzacja<br /> <br /> alufelgi<br /> <br /> elektryka<br /> <br /> lokalizacja : Kraków  Nowa Huta<br /> <br />  proszę dzwonić lub pisać sms    z braku czasu nie pilnuję zbytnio maili - zainteresowany - proszę dzwonić lub pisać sms",
        "price": 11400,
        "milage": 230000,
        "model": "Colt",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "XMCXNZ34A9F008420",
    },
    {
        "clasfieds_id": 828979997,
        "title": "Mazda 6 Mazda 6 gj 2016r polift.Tylko 63 tys km.max opcja.",
        "description": "Witam serdecznie. Sprzedam Mazde 6 GJ z 2016 roku polift. Max wyposażone head up display, radar,skora aktywny tempomat system naglosnienia bose i wiele innyych. Auto przyprowadzone ze Stanow Zjednoczonych jestem pierwszym właścicielem w kraju. Auto z bardzo malym przebiegiem 63800 km bardzo dobrze wyposażone, nie wymaga zadnego wkladu finansowego. Świeżo po serwisie filtrowo olejowym, OC jak i PT oplacone na rok.Prosze tylko konkretnie zainteresowane osoby szanuje swoj i Państwa czas. Cena do negocjacji po obejrzeniu auta i jezdzie probnej.Wiecej informacji na temat auta udziele telefonicznie. Pozdrawiam.",
        "price": 72900,
        "milage": 63700,
        "model": "6",
        "condition": "Nieuszkodzony",
        "country_origin": "Stany Zjednoczone",
        "vin": "JM1GJ1W53G1409795",
    },
    {
        "clasfieds_id": 838380606,
        "title": "Nissan Qashqai Nissan Qashqai 1.2 BENZYNA opony lato/zima, kamery 360,super stan",
        "description": 'Auto zarejestrowane w pięknym kolorze biała perła, serwisowane   i ubezpieczone w Polsce,  niski przebieg tylko 118 tys. km 2 kluczyki , dwa komplety opon lato/zima, nowy akumulator BOSCH  z 2 letnią gwarancją <br /> bogata wersja wyposażenia <br /> KAMERY 360<br /> System Keyless Go<br /> Nawigacja <br /> ABS + EBD<br /> Inteligentny system wspomagania hamowania<br /> ESP<br /> RADAR<br /> asystent pasa ruchu <br /> tempomat<br /> limiter prędkości<br /> rozpoznawanie znaków<br /> podgrzewane fotele <br /> automatyczna zmiana świateł mijania/drogowe<br /> System wspomagania ruszania pod górę z funkcja Auto Hold<br /> Automatyczne wycieraczki i czujnik deszczu<br /> Elektryczny hamulec postojowy<br /> System pomiaru ciśnienia w oponach<br /> System audio z radiem/CD, MP3, AUX, USB i iPod, Bluetooth<br /> 6 głośniki<br /> Wyświetlacz TFT 5” zintegrowany z zestawem wskaźników<br /> Światła do jazdy dziennej w technologii LED<br /> Tylne światła w technologii LED<br /> Wszystkie szyby elektryczne <br /> Kolumna kierownicy z regulacją w dwóch płaszczyznach<br /> System Start/Stop<br /> Lusterka zewnętrzne regulowane i podgrzewane elektrycznie ze zintegrowanymi kierunkowskazami LED<br /> Miękką skórę na kierownicy oraz gałce dźwigni zmiany biegów<br /> Podświetlaną obwódkę gałki zmiany biegów<br /> 17" felgi ze stopów metali lekkich<br /> Przednie lampy przeciwmgłowe<br /> Ręcznie regulowane podparcie odcinka lędźwiowego w fotelu kierowcy i pasażera<br /> Automatycznie składane lusterka<br /> kontakt',
        "price": 73900,
        "milage": 118000,
        "model": "Qashqai",
        "condition": "Nieuszkodzony",
        "country_origin": "Finlandia",
        "vin": "SJNFEAJ11U2169454",
    },
]

non_fraulent_offers = [
    {
        "clasfieds_id": 731031843,
        "title": "Hyundai I30 Wersja Modern + Pakiet Desing OD RĘKI !!!",
        "description": "Opiekun Ogłoszenia: Patryk Skrudlik tel. <br /> <br /> Prosimy o kontakt telefoniczny przed Państwa wizytą w naszym salonie w celu potwierdzenia dostępności samochodu<br /> <br /> MOŻLIWE MIEJSCE ODBIORU SAMOCHODU<br /> ──────────<br /> ■Bielsko-Biała ■ Częstochowa ■ Rybnik<br /> ──────────<br /> DANE SZCZEGÓŁOWE<br /> ──────────<br /> MODEL: Hyundai i30  1.0 T-GDI 6MT (120KM)<br /> WERSJA: Modern  + pakiet Design<br /> KOLOR / KOD: Shimmering silver <br /> <br /> ──────────<br /> INFORMACJE CENOWE<br /> ──────────<br /> <br /> ► Cena 86.900 zł<br /> <br /> ──────────<br /> FINANSOWANIE<br /> ──────────<br /> ✔ Kredyt 50 / 50<br /> ✔ Kredyt 3 x 33%<br /> ✔ Kredyt Nisko Oprocentowany<br /> ✔ Okres kredytowania nawet do 10 lat<br /> ✔ Leasing operacyjny<br /> ✔ Leasing finansowy<br /> ✔ Najem długoterminowy<br /> ──────────<br /> WYPOSAŻENIE<br /> ──────────<br /> BEZPIECZEŃSTWO<br /> - Poduszki bezpieczeństwa przednie<br /> - Poduszki bezpieczeństwa boczne i kurtynowe<br /> - System ABS z elektroniczną kontrolą stabilizacji (ESC) i asystentem podjazdu (HAC)<br /> - Mocowania ISOFIX na tylnych fotelach<br /> - Blokada zapobiegająca otwarciu tylnych drzwi przez dzieci<br /> - Elektryczne wspomaganie kierownicy<br /> - Kolumna kierownicza regulowana w dwóch płaszczyznach<br /> <br /> ZEWNĘTRZNE<br /> - Szyba tylna podgrzewana z wyłącznikiem czasowym<br /> - Reflektory halogenowe (światła mijania) z funkcją statycznego doświetlania zakrętów<br /> - Automatyczne włączanie świateł<br /> - Światła do jazdy dziennej LED<br /> - Tylny spoiler z trzecim światłem stop<br /> - Trzecie światło stop LED<br /> - Przednie światła przeciwmgielne<br /> - Kierunkowskazy w przednich błotnikach<br /> - Boczne lusterka w kolorze nadwozia<br /> - Lusterka boczne elektrycznie sterowane i podgrzewane<br /> - Relingi dachowe<br /> - Klamki zewnętrzne w kolorze nadwozia<br /> - Felgi stalowe 15” z kołpakami<br /> <br /> WEWNĘTRZNE<br /> - Fotel kierowcy z regulacją wysokości<br /> - Tylna kanapa składana w proporcji 60:40<br /> - Zagłówki tylne z regulacją wysokości<br /> - Tapicerka materiałowa w ciemnej tonacji<br /> - Szyby sterowane elektrycznie (kierowcy z funkcją Auto Down)<br /> - Oświetlenie pierwszego rzędu + schowek na okulary<br /> - Oświetlenie drugiego rzędu<br /> - Oświetlenie przestrzeni bagażowej<br /> - Przedni podłokietnik ze schowkiem<br /> - Dwupoziomowa podłoga bagażnika<br /> - Klimatyzacja manualna<br /> - Komputer pokładowy z 3,5” kolorowym wyświetlaczem<br /> - Asystent utrzymywania pasa ruchu (LKA), monitorowanie uwagi kierowcy (DAW), informowanie o odjechaniu poprzedzającego pojazdu (LVDA)<br /> - Asystent unikania kolizji czołowych (FCA) z wykrywaniem pieszych<br /> - Ogranicznik prędkości<br /> - Tylne czujniki parkowania<br /> <br /> AUDIO<br /> - Radio z RDS + DAB<br /> - Głośniki w drzwiach przednich<br /> - Głośniki w drzwiach tylnych<br /> - System Bluetooth<br /> ──────────<br /> PROGRAM GWARANCYJNY<br /> ──────────<br /> ■ 5 lat gwarancji bez limitu kilometrów<br /> ■ 5 lat assistance w Polsce i za granicą<br /> ■ 5 lat bezpłatnej kontroli stanu technicznego<br /> ■ 5 lat gwarancji na lakier<br /> ■ 8 lat na baterię wysokiego napięcia<br /> ■ 12 lat gwarancji na perforację nadwozia<br /> ──────────<br /> INFORMACJE DODATKOWE<br /> ──────────<br /> ǃ Przyjmujemy w rozliczeniu samochody używane wszystkich marek.<br /> <br /> Niniejsze ogłoszenie jest wyłącznie informacja handlową i nie stanowi oferty w myśl art. 66, paragraf 1. Kodeksu Cywilnego. Sprzedający nie odpowiada za ewentualne błędy lub nieaktualność ogłoszenia.<br /> <br /> Oferta jest ważna w momencie zakupu za gotówkę lub w finansowaniu zrealizowanym przez Spółkę.<br /> ──────────<br /> INFORMACJE O FIRMIE<br /> ──────────<br /> STAWOWY GROUP Spółka z ograniczoną odpowiedzialnością Spółka komandytowa<br /> <br /> Autoryzowany Dealer Hyundai<br /> <br /> Bielsko-Biała, ul. Czarna 22<br /> Nowa Wieś k. Częstochowy, ul. Krakowska 8<br /> Rybnik, ul. Gliwicka 114<br /> www.stawowy.hyundai.pl",
        "price": 86900,
        "milage": 5,
        "model": "i30",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "TMAH251BANJ196757",
    },
    {
        "clasfieds_id": 744052926,
        "title": "Jaguar F-Pace MY22 2.0 I4 250 PS AWD Auto R-Dynamic SE",
        "description": "Autoryzowany Dealer Jaguar/ Land Rover w Długołęce k. Wrocławia proponuje zakup samochodu:<br /> <br />  F-Pace MY22 2.0 I4 250 PS AWD Auto R-Dynamic SE<br /> <br />  KONTAKT:   <br /> <br /> Kolor lakieru : <br /> Bluefire Blue<br /> <br />  Kolor wnętrza : <br /> Ebony/Light Oyster<br /> <br />  DANE TECHNICZNE: <br /> <br />  VIN:  SADCA2BX6NA693419<br />  Pojemność silnika :   1997 cm<br />  Moc:  250 KM <br /> <br />  CENA KATALOGOWA: </b  363 090 PLN<br />    CENA SPECJALNA: 299 900PLN <br /> <br /> Informacje zaprezentowane na stronach niniejszego serwisu nie stanowią oferty w rozumieniu przepisów Kodeksu Cywilnego. Szczegółowe warunki sprzedaży, wyposażenie prezentowanych samochodów, ceny oraz aktualność oferty finansowania zakupu prosimy potwierdzić kontaktując się bezpośrednio z naszym salonem.<br /> <br /> <b> WYPOSAŻENIE DODATKOWE:  <br /> <br /> - Zestaw audio Meridian™ Sound System - 13 głośników<br /> - Bezprzewodowy system do ładowania telefonu<br /> - PAKIET COLD CLIMATE<br /> - Podgrzewane siedzenia przednie regulowane w 14 kierunkach<br /> - Przyciemniane szyby<br /> - Zewnętrzny pakiet stylistyczny Black<br /> <br />  WYPOSAŻENIE PODSTAWOWE:  <br /> <br /> -  System bezkluczykowego otwierania/zamykania samochodu<br /> - System monitorowania ciśnienia w oponach TPMS<br /> - Autonomiczny system awaryjnego hamowania<br /> - Asystent martwego punktu<br /> - Kamera cofania<br /> - Czujnik bezpiecznego wysiadania dla pasażerów z tyłu<br /> - Tempomat z ogranicznikiem prędkości<br /> - System monitorujący zmęczenie kierowcy<br /> - Czujniki parkowania<br /> - Elektrycznie otwierana i zamykana klapa bagażnika<br /> - Siedzenia przednie regulowane w 14 kierunkach<br /> - Dwustrefowa automatyczna klimatyzacja<br /> <br />  KONTAKT:   <br /> <br /> Od samego początku naszej działalności marki Jaguar i Land Rover były dla nas przede wszystkim pasją. Rosnące zaufanie ze strony Klientów jest dla nas motywacją do ciągłego rozwoju i otwierania się na ich aktualne potrzeby i oczekiwania. Dlatego stworzyliśmy najnowocześniejszy salon i serwis w tej części Europy, do którego serdecznie Państwa zapraszamy.",
        "price": 299900,
        "milage": 5,
        "model": "Pozostałe Jaguar",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "SADCA2BX6NA693419",
    },
    {
        "clasfieds_id": 761674517,
        "title": "Ford Mustang Ford Mustang GT Mach 1 MANUAL Tremec od ręki OPOLE",
        "description": "Witamy serdecznie w ogłoszeniu<br /> <br /> FordStore BCH Chwaliński z Opola , Autoryzowany Dealer marki Ford z 27-letnim doświadczeniem oferuje LIMITOWANY legendarny model MACH-1 z automatyczną skrzynią biegów.<br /> Termin odstawy : 7 dni roboczych<br /> Moc silnika<br /> 460 KM (338 kW) przy 7250 obr/min<br /> Skrzynia hydrokinetyczna o dziesięciu przełożeniach<br /> Maksymalny moment obrotowy<br /> 529 Nm przy 4900 obr/min<br /> Przyspieszenie 0-100 km/h (0-62 mph), 4,8 sekundy .<br /> Nowe oblicze Ikony motoryzacji, o niesamowitych osiągach i brzmieniu.<br /> <br /> ─────────────────────────────────────────────────────<br /> <br /> OFERUJEMY MOŻLIWOŚĆ ZAKUPU BEZ WYCHODZENIA Z DOMU.<br /> OFERUJEMY MOŻLIWOŚĆ PRZEPROWADZENIA WIDEO-INSPEKCJI DLA WYBRANEGO PRZEZ PAŃSTWA SAMOCHODU.<br /> <br /> ────────────────────────────────────────────────────<br /> <br /> Auto z rocznika  2022 . <br /> Termin realizacji 10 dni roboczych. <br /> Auto z pierwszą rejestracja na Dilera<br /> Fabrycznie nowe z pełna gwarancja podstawową<br /> FORMY FINANSOWANIA:<br /> - Leasing<br /> - Kredyt<br /> - Wynajem długoterminowy<br /> <br /> Wystawiamy fakturę VAT<br /> ─────────────────────────────────────────────────────<br /> Wyposażenie opcjonalne zawarte w prezentowanym egzemplarzu<br /> Lakier specjalny Cyber Orange<br /> Autoalarm – Thatcham, obwodowy i pojemnościowy<br /> <br /> GWARANCJA<br /> <br /> • 2-letnia gwarancja na części mechaniczne<br /> • 12 letnia na perforacje nadwozia<br /> • Możliwość przedłużenia ochrony gwarancyjnej nawet do 6 lat lub 180 000km dzięki usłudze Ford Protect<br /> ─────────────────────────────────────────────────────<br /> ODKUP SAMOCHODÓW<br /> Chętnie wycenimy do Ciebie samochód każdej marki.<br /> ─────────────────────────────────────────────────────<br /> ZAPRASZAMY NA JAZDĘ PRÓBNĄ ORAZ DO KONTAKTU Z NASZYMI DORADCAMI HANDLOWYMI<br /> <br /> Krzysztof Stolecki  kstoleckichwalinski.com.pl<br /> Krzysztof Pyka   kpykachwalinski.com.pl<br /> ─────────────────────────────────────────────────────<br /> Niniejsze ogłoszenie nie stanowi oferty w myśl art. 66 § 1. Kodeksu Cywilnego.<br /> Samochód prezentowany na zdjęciach może się różnić od przedstawionego w opisie.<br /> Celem ustalenia dostępności pojazdu, prosimy o kontakt z doradcą handlowym.",
        "price": 290100,
        "milage": 10,
        "model": "Mustang",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "1FA6P8R07N5550559",
    },
    {
        "clasfieds_id": 766504604,
        "title": "Ford Mustang Ford Mustang MACH 1",
        "description": 'Witamy serdecznie,<br /> Jako Autoryzowany Dealer Marki Ford – FordStore Łódź – oferujemy Państwu:<br /> FORD Mustang MCA MACH 1, FASTBACK, 5.0 V8 460KM, AUTOMATYCZNA A10 Mach 1<br /> <br /> Zadzwoń i poznaj szczegóły<br /> Zapraszamy do kontaktu z naszymi doradcami handlowymi:<br /> <br /> Damian Boczek: tel.  , mail: dboczekfordstore-lodz.pl<br /> Marek Kopka: tel.  , mail: mkopkafordstore-lodz.pl<br /> <br /> Wyposażenie dodatkowe zawarte w cenie pojazdu:<br /> <br /> Lakier metalizowany Fighter Jet Grey <br /> * Ze stopów lekkich - 19" x 9,5" z przodu, 19" x 10" z tyłu, wzór MACH 1, lakierowane w kolorze High Gloss Magnetic,<br /> ogumienie z przodu: 255/40/19; ogumienie z tyłu: 275/40/19<br /> * Pakiet stylizacyjny Mach 1 <br /> - fotele z tapicerką częściowo skórzaną Cactus Grey/ Orange  <br /> - pasy wzdłuż boków nadwozia <br /> - pasy na masce <br /> - zaciski hamulców lakierowane na pomarańczowo<br /> <br /> Gwarancja Producenta:<br /> <br /> * 2-letnia gwarancja na części mechaniczne<br /> * Możliwość przedłużenia ochrony gwarancyjnej nawet do 5 lat dzięki usłudze Ford Protect<br /> * 12-letnia gwarancja na perforację nadwozia<br /> <br /> Informacje zaprezentowane na stronie internetowej nie stanowią oferty w rozumieniu przepisów Kodeksu Cywilnego ( art.66). Zawarte w niniejszej publikacji informacje nie stanowią również zapewnienia w rozumieniu art.4 ust. 3 i 4 Ustawy z dnia 27 lipca 2002 roku o szczególnych warunkach sprzedaży konsumenckiej oraz zmianie Kodeksu Cywilnego, a także nie stanowią opisu towaru w rozumieniu art. 4 ust. 2. Indywidualne uzgodnienie właściwości i specyfikacji pojazdu następuje w umowie jego sprzedaży. Zdjęcia mają charakter poglądowy.',
        "price": 306500,
        "milage": 1,
        "model": "Mustang",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "1FA6P8R00N5550564",
    },
    {
        "clasfieds_id": 772361212,
        "title": 'Mitsubishi Space Star "od ręki" Android Auto Apple Car',
        "description": "Autoryzowany Dealer MITSUBISHI w Toruniu Arpol Motor Company ma przyjemność zaoferować:<br /> <br /> Model Mitusbishi Space Star z możliwością skorzystania z kredytu 0% w opcji 50/50<br /> <br /> Więcej informacji o modelu pod adresem: https://www.mitsubishi.torun.pl/samochody/space-star<br /> <br /> Serdecznie zapraszamy na oględziny oraz do rezerwacji!<br /> <br /> Bezpośredni kontakt do sprzedawcy<br /> <br /> Szymon Jędrzejewski, tel. <br /> Roman Drużyński, tel.  <br /> <br /> ARPOL Motor Company – autoryzowany salon Mitsubishi oraz aut używanych.<br /> Ul. Szosa Bydgoska  Toruń<br /> <br /> Salon otwarty:<br /> Poniedziałek – Piątek : 9:00 – 18:00<br /> Sobota – 9:00 – 14:00<br /> <br /> *Cena nie zawiera dopłaty za lakier<br /> *Cena uwzględnia rabat za skorzystanie z ubezpieczenia oraz finansowania w salonie Arpol.<br /> <br /> Niniejsze ogłoszenie jest wyłącznie informacją handlową i nie stanowi oferty w myśl art. 66, paragraf 1. Kodeksu Cywilnego. Sprzedający nie odpowiada za ewentualne błędy lub nieaktualność ogłoszenia.",
        "price": 64490,
        "milage": 5,
        "model": "Space Star",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "MMCXNA03APH001302",
    },
    {
        "clasfieds_id": 774371057,
        "title": "Fiat 500 ICON 3+1 CVT 118KM Pełny Elektryk! Dostępny od ręki!",
        "description": "Autoryzowany Salon Fiat Auto Spektrum oferuje:<br /> <br /> Model: Fiat 500E ICON 3+1<br /> <br /> Samochód świeżo zarejestrowany. Bez przebiegu!<br /> <br /> Cena katalogowa 167300zł<br /> <br /> Samochód dostępny od ręki!<br /> <br /> Dbając o cenny czas naszych Klientów wszystkie formalności związane z finansowaniem zakupu oraz ubezpieczeniem pojazdu przeprowadzamy na miejscu.<br /> <br /> Oferujemy również możliwość pozostawienia w rozliczeniu samochodu każdej marki.<br /> <br /> Serdecznie zapraszamy do naszego salonu Fiata - na rynku tarnowskim funkcjonujemy od kilkunastu lat, zatem nasza marka to lata zdobytej wiedzy, doświadczenia oraz zaufania i lojalności Klientów. W sprzedaży posiadamy pełną gamę samochodów marki Fiat oraz Fiat Professional. Od 2017 roku jesteśmy częścią GRUPY AUTO SPEKTRUM, dzięki czemu możemy jeszcze lepiej dopasować ofertę do Państwa potrzeb.<br /> <br /> Niniejsze ogłoszenie jest wyłącznie informacją handlową, która nie stanowi oferty w myśl art 6, par. 1 Kodeksu Cywilnego. Sprzedający nie ponosi odpowiedzialności za ewentualne błędy lub nieaktualność ogłoszenia.",
        "price": 148200,
        "milage": 1,
        "model": "500",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "ZFAEFAR47NX093007",
    },
    {
        "clasfieds_id": 774780676,
        "title": "Dodge Challenger fabrycznie nowy 2022r kamera pakiet zimowy VAT23",
        "description": "Sprzedawca:<br /> Autoryzowany DEALER samochodów DODGE / RAM w Toruniu<br /> <br /> Auto Toruń to oficjalny dealer samochodów DODGE/RAM w Polsce<br /> <br /> AUTO DOSTĘPNE W SALONIE DO NATYCHMAISTOWEGO ODBIORU<br /> <br /> Zapraszamy do kontaktu z działem handlowym:<br /> <br /> Tomasz <br /> <br /> Przedmiot sprzedaży:<br /> <br /> Dodge Challenger SXT MY2022<br /> Silnik Pentastar: 3,6L 305 HP / 363 Nm<br /> Skrzynia biegów: 8-biegowy automat – Napęd na tylną oś<br /> Kolor szary: bordowy Octane Red Pearl Coat<br /> Tapicerka materiałowa czarna<br /> <br /> Wyposażenie:<br /> AJV - Grupa wygody kierowcy AJV:<br /> - Elektrycznie regulowane lusterka boczne<br /> - Reflektory wyładowcze o wysokiej intensywności<br /> - Wykrywanie martwego pola i ścieżki krzyżowej<br /> <br /> ADE - Pakiet Zima:<br /> - Podgrzewane przednie fotele<br /> - Podgrzewana kierownica<br /> - Zdalne uruchamianie pojazdu<br /> - Podgrzewana tylna szyba<br /> <br /> UAQ - Pakiet Multimedialny:<br /> - System Uconnect 4C NAV<br /> - Dotykowy ekran o przekątnej 8.4 cala<br /> - Nawigacja EU<br /> - Menu w języku polskim<br /> - Google Android Auto<br /> - Apple CarPlay<br /> - Wejścia USB<br /> - Bluetooth<br /> <br /> ATL - Pakiet Alpine Audio:<br /> - Subwoofer<br /> - 9 głośników<br /> - Wzmacniacz 506W<br /> <br /> Wyposażenie standardowe:<br /> - Asystent hamowania<br /> - Asystent ruszania pod górę<br /> - 3 mocowania ISOFIX<br /> - Składana tylna kanapa 60/40<br /> - Dywaniki welurowe<br /> - Automatycznie przyciemniane lusterko wsteczne<br /> - Czujniki cofania<br /> - Kamera cofania<br /> - Klimatyzacja automatyczna dwustrefowa<br /> - Elektrycznie regulowany fotel kierowcy<br /> - Automatyczne światła mijania<br /> - Światła do jazdy dziennej LED<br /> - Alarm i Immobiliser<br /> - Skórzana kierownica<br /> - Elektrycznie regulowana kolumna kierownicy<br /> - Tryb jazdy SPORT<br /> - Czujniki ciśnienia opon<br /> <br /> Samochód fabrycznie nowy dostosowany do wymogów europejskich<br /> <br /> Sprzedaż na podstawie Fv VAT23%",
        "price": 259000,
        "milage": 20,
        "model": "Pozostałe Dodge",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "2C3CDZAG3NH125048",
    },
    {
        "clasfieds_id": 779932740,
        "title": "Jaguar I-Pace Nowa cena! Elektryk 4x4, zasieg 470 km, 400 KM,",
        "description": 'Nowy w Trójmieście Autoryzowany Salon i Serwis Jaguar i Land Rover – firma BRITISH AUTO ZDUNEK oferuje do sprzedaży:<br /> <br /> Jaguar I-Pace MY23 EV 400 PS AWD Auto SE<br /> Dostępność: dostępny od października<br /> Silnik: 2 silniki elektryczne o mocy łącznie 400 KM i momencie obrotowym 696 Nm<br /> Kolor: Eiger Grey – szary metalizowany<br /> Wnętrze: Tapicerka skórzana Duo Leather w kolorze Ebony, wnętrze w kolorze Ebony/Ebony<br /> Wersja wyposażenia: SE<br /> Rok produkcji: 2022<br /> Osiągi: przyspieszenie 0-100 km/h 4,8 s. , prędkość maksymalna 200 km/h<br /> Pojemność baterii: 90 kWh, zasięg w cyklu WLTP do 470 km<br /> <br /> Cena katalogowa prezentowanego samochodu: 477 780 PLN.<br /> Cena promocyjna 349 000 brutto<br /> 379 000 pln  najniższa cena w okresie 30 dni przed wprowadzeniem ostatniej obniżki.<br /> <br /> Oferujemy:<br /> Możliwości finansowania: leasing, wynajem, kredyt, gotówka!<br /> Korzystne pakiety ubezpieczeń OC/AC/NNW/GAP!<br /> Możliwość pozostawienia samochodu w rozliczeniu! <br /> Transport samochodu pod dom!<br /> Zabezpieczenie lakieru: powłoki ceramiczne, folie ochronne!<br /> <br /> WYPOSAŻENIE STANDARDOWE:<br /> <br /> Przednie siedzenia regulowane w 14 kierunkach z pamięcią ustawień (w 12 kierunkach elektrycznie z manualną regulacją wysokości zagłówka w 2 kierunkach)<br /> Tylna kanapa składana 40:20:40 z podłokietnikiem<br /> Czarna wykładzina podłogi<br /> Wykończenie wnętrza - Gloss Black<br /> Kierownica sportowa wykończona skórą drobnoziarnistą<br /> Metalowe nakładki progów z napisem Jaguar<br /> Podsufitka Morzine w kolorze Light Oyster<br /> Lusterko wewnętrzne elektrochromatyczne (funkcja przyciemniania automatyczna)<br /> Oświetlenie wnętrza 2 - rozszerzone<br /> Dwustrefowa klimatyzacja<br /> Moduł wstępnego elektrycznego ogrzewania kabiny<br /> Radio cyfrowe DAB - dostępność sygnału i stacji zgodnie z ofertą nadawców<br /> Android Auto™<br /> Apple CarPlay®<br /> Remote<br /> Pivi Pro<br /> Wyświetlacz Touch Pro 10"<br /> Dostęp bezkluczykowy<br /> Alarm perymetryczny<br /> System monitorowania ciśnienia w oponach TPMS<br /> Voice Control - sterowanie głosowe niektórymi funkcjami nawigacji. audio i Bluetooth (komendy w języku angielskim)<br /> System awaryjnego hamowania<br /> Asystent martwego punktu<br /> Kamera cofania<br /> Czujnik bezpiecznego wysiadania z samochodu<br /> Adaptacyjny tempomat z asystentem utrzymania pasa ruchu<br /> System monitorujący zmęczenie kierowcy<br /> System wspomagający utrzymanie prawidłowego pasa ruchu<br /> System wykrywania ruchu przecinającego drogę cofania z automatycznym hamulcem<br /> System rozpoznawania znaków drogowych z inteligentnym ogranicznikiem prędkości ASL<br /> Przewód do ładowania akumulatorów (Wall box oraz publiczne stacje ładowania)<br /> Otwarty mechanizm różnicowy z systemem stabilizacji toru jazdy za pomocą układu hamulcowego<br /> Spolier na tylnej klapie<br /> Oznaczenie EV400<br /> Wzmocnione i laminowane szyby boczne<br /> Przednia szyba o obniżonej przepuszczalności promieniowania podczerwonego<br /> Lusterka zewnętrzne w kolorze nadwozia - elektrycznie regulowane, podgrzewane, składane, elektrochromatyczne, z lampkami doświetlającymi podłoże, z wbudowanymi kierunkowskazami i z pamięcią ustawień<br /> Lampy przednie Premium LED ze światłami obrysowymi LED<br /> Spryskiwacze reflektorów<br /> Elektrycznie otwierana i zamykana klapa bagażnika<br /> Felgi aluminiowe 20" 6-ramienne (wzór 6007)<br /> Zestaw naprawczy do opon<br /> <br /> WYPOSAZENIE OPCJONALNE:<br /> <br /> Przednie siedzenia podgrzewane ze zintegrowanym zagłówkiem, regulowane w 14 kierunkach z pamięcią ustawień fotela kierowcy<br /> Pakiet Premium Black<br /> Dywaniki<br /> Wykończenie wnętrza - Monogram Aluminium<br /> Podsufitka Morizine w kolorze Ebony<br /> Panel Touch Pro Duo<br /> Bezprzewodowy system do ładowania telefonu<br /> System nagłaśniający Meridian™ Sound System<br /> <br /> PAKIET COLD CLIMATE<br />   - Podgrzewana przednia szyba<br />   - Podgrzewane dysze spryskiwaczy szyby przedniej<br />   - Podgrzewana kierownica<br /> Przewód do ładowania akumulatorów (domowego użytku)<br /> Dach panoramiczny stały<br /> Przyciemniane szyby<br /> Przednie podwójne uchwyty na kubki<br /> Felgi aluminiowe 20" 6-ramienne (wzór 6007) – Gloss Dark Grey, wykończenie Diamond Turned<br /> Eiger Grey - lakier metalik<br /> Siedzenia Performance z tapicerką DuoLeather w kolorze Ebony z wnętrzem Ebony/Ebony<br /> <br /> Zapraszamy do kontaktu w celu umówienia terminu prezentacji / jazdę próbnej!<br /> Specjaliści ds. sprzedaży samochodów:<br /> Maciej Kołakowski<br /> Marek Dyktyński',
        "price": 349000,
        "milage": 7,
        "model": "Pozostałe Jaguar",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "SADHA2B1XP1627556",
    },
    {
        "clasfieds_id": 787041095,
        "title": "Opel Astra Opel Astra Hatchback Elegance 1.2 Turbo 130 KM M6 Start/Stop",
        "description": 'Autoryzowany dealer marki OPEL ASW Wojciula Sp. z o.o. oferuje Państwu samochód Opel Astra  HATCHBACK ELEGANCE z sinikiem 1.2 Turbo 130 KM M6 Start/Stop.<br /> <br /> ZAPRASZAMY DO KONTAKTU:<br /> <br /> Daniel Kołodziński - tel. <br /> Jakub Sidz - tel. <br /> <br /> WYPOSAŻENIE DODATKOWE OFEROWANEGO SAMOCHODU:<br /> <br /> 1\tPRZYGOTOWANIE DO MONTAŻU KOŁA ZAPASOWEGO\tT7Y.<br /> 2\tSZARY - VULKAN, METALICZNY\tG40.<br /> 43\tTAPICERKA ISABELLA, MATERIAŁOWA, W KILKU ODCIENIACH JASNEJ SZAROŚCI ŁĄCZONA Z CZARNĄ SZTUCZNĄ SKÓRĄ, FOTEL KIEROWCY AGR + OGRZEWANIE<br /> <br /> WYPOSAŻENIE STANDARDOWE OFEROWANEGO SAMOCHODU:<br /> <br /> 1\t10" wyświetlacz kierowcy\tXX04\t<br /> 2\t6 głośników\tUW5.\t<br /> 3\t8 barw oświetlenia ambientowego do wyboru\tXX16\t<br /> 4\t8 poduszek powietrznych\tXX06\t<br /> 5\tAutomatyczne włączanie świateł drogowych\tTQ5.\t<br /> 6\tAutomatyczne włączanie świateł mijania - czujnik zmierzchu\tT83.\t<br /> 7\tBezkluczykowy dostęp do auta i zapłon uruchamiany przyciskiem\tXX10\t<br /> 8\tBezramkowe elektrochromatyczne lusterko wsteczne\tXX07\t<br /> 9\tChromowane listwy wzdłuż okien\tMDQ.\t<br /> 10\tCzujnik deszczu\tXX08\t<br /> 11\tCzujniki parkowania przód i tył (8)\tUD5.\t<br /> 12\tDach w kolorze nadwozia\tNTO.\t<br /> 13\tDostosowanie prędkości do znaków, wymaga akceptacji kierowcy\tISA.\t<br /> 14\tElektryczne szyby przednie i tylne\tAEF.\t<br /> 15\tFelgi aluminiowe 17", wzór Admiral, diamentowy szlif srebrny, czarne wnętrze\tPYQ.\t<br /> 16\tHamulce: tarczowe, elektryczny hamulec postojowy, wspomaganie ruszania pod górę (2 <br />    sekundy, >3% nachylenia), ABS, EBD, EBA PCBS, ASR, ESC, TSM\tXX05\t<br /> 17\tKlimatyzacja elektroniczna dwustrefowa z filtrem przeciwpyłkowym i przeciwzapachowym\t <br />    CJ2.\t<br /> 18\tMonitorowanie ciśnienia w oponach\tUJO.\t<br /> 19\tOpony  225/45 R17 - 94V\tQLD.\t<br /> 21\tPodłokietnik kierowcy, otwarty schowek z miejscem na kubki z przodu dla skrzyni <br />    manualnej, mały schowek z roletą dla skrzyni automatycznej\tXX12\t<br /> 22\tPrzygotowanie do montażu haka\tV3O.\t<br /> 23\tPure Panel Pro 10"\tU2R.\t<br /> 24\tRadio bez nawigacji\tU1F.\t<br /> 25\tRadio cyfrowe DAB\tU2Q.\t<br /> 26\tRadio z 7 kolorami podświetlenia do wyboru, 2 USB C 15W, Bluetooth, bezprzewodowa <br />    projekcja telefonu, system e-call/b-call i OpelConnect, 7 filmów instruktażowych, zdalna <br />    aktualizacja systemu (U2R&UW5&U1F&U2Q)\tCR37\t<br /> 27\tReflektory LED\tT4L.\t<br /> 28\tReflektory przeciwmgielne\tT3U.\t<br /> 29\tRęczne poziomowanie świateł\tTR6.\t<br /> 30\tSkórzana kierownica ścięta u dołu\tN35.\t<br /> 31\tSystem automatycznego hamowania oparty na radarze AEBS3 wykrywający pojazdy, <br />    rowerzystów, także w nocy\tUGN.\t<br /> 32\tSystem wykrywania zmęczenia kierowcy\tAHM.\t<br /> 33\tSzyby boczne przyciemniane\tAKO.\t<br /> 34\tTempomat adaptacyjny\tK59.\t<br /> 35\tTylna kamera 180 stopni\tUVP.\t<br /> 36\tTylna kanapa z otwieranym podłokietnikiem (z miejscem na 2 kubki), który ujawnia otwór na <br />    narty\tXX13\t<br /> 37\tUtrzymanie w pasie ruchu LKA\tUHX.\t<br /> 38\tZaawansowany system rozpoznawania znaków drogowych ETSR\tUVX.\t<br /> 39\tZderzak "Elegance"\tV4F.\t<br /> 40\tZestaw naprawczy do opon\tKTI.\t<br /> 41\t4-kierunkowa regulacja lędźwiowa kierowcy, elektryczna\tAVK.\t<br /> 42\t6-kierunkowa regulacja fotela pasażera (przód-tył, góra-dół, pochylenie oparcia, manualne)\t <br />    A7D.\t<br /> 43\t8-kierunkowa regulacja fotela kierowcy (przód-tył, góra-dół, pochylenie siedziska, <br />    pochylenie oparcia, manualne)\tA2Y.\t<br /> 44\tPodgrzewana kierownica\tUVD.\t<br /> 45\tPodgrzewane fotele przednie\tKA1.\t<br /> 46\tPrzednie fotele ergonomiczne\tAE4.\t<br /> 47\tWysuwana poduszka podudziowa kierowcy\tAHC.\t<br /> 48\tZagłówki przednich foteli regulowane góra/dół, przód-tył\tAHR.\t<br /> 49\tCzarne lusterka, elektrycznie składane z migaczami LED\tXX03\t<br /> 50\tTylna kanapa dzielona w stosunku 60/40\tXX01<br /> <br /> ZAPRASZAMY DO KONTAKTU:<br /> <br /> Daniel Kołodziński - tel. <br /> Jakub Sidz - tel. <br /> <br /> Zapraszamy także do odwiedzin naszego salonu oraz serwisu ASW Wojciula . Przed przyjazdem, prosimy o kontakt z naszym działem sprzedaży samochodów osobowych Opel który uzgodni z Państwem dogodne warunki wizyty w salonie, a także poinformuje o dostępności samochodu, gdyż znajduje się on w ciągłej sprzedaży.<br /> <br /> W naszych salonach zaproponujemy wygodne oraz odpowiednie formy finansowania zakupu w postaci - kredytu, leasingu lub wynajmu długoterminowego, a także, zajmiemy się załatwieniem wszelkich formalności związanych z rejestracją samochodu oraz uzyskaniem ubezpieczenia<br /> <br /> Niniejsze ogłoszenie jest wyłącznie informacją handlową i nie stanowi oferty w myśl art. 66, § 1. Kodeksu Cywilnego<br /> <br /> P',
        "price": 105000,
        "milage": 2,
        "model": "Astra",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "VXKFPHNSLN1036635",
    },
    {
        "clasfieds_id": 789922338,
        "title": "Fiat Tipo Cross +3 lata gwarancji",
        "description": "Zapraszamy do naszego Salonu w Tychach przy ulicy Begonii 12.<br /> <br /> Samochód zarejestrowany przebieg 0 km<br /> <br /> Jesteśmy Autoryzowanym Dealerem marki Fiat i Fiat Professional, Jeep, Alfa Romeo.<br /> Na miejscu załatwiamy wszelkie formalności związane z zakupem (kredyt, leasing, ubezpieczenie).<br /> <br /> Niniejsze ogłoszenie ma charakter informacyjny i nie stanowi wiążącej oferty handlowej w rozumieniu art. 66 kodeksu Cywilnego.<br /> <br /> Zapraszamy do naszego salonu w godzinach:<br /> poniedziałek-piątek: 8.00-18.00<br /> sobota: 9.00-14.00<br /> <br /> ☎ Dodatkowe informacje na temat ogłoszenia udzielimy pod numerem<br /> <br /> Jerzy Szydlik– Specjalista ds. Sprzedaży<br /> kom.: <br /> e-mail j.szydlik(a)fcakierat.pl",
        "price": 89900,
        "milage": 1,
        "model": "Tipo",
        "condition": "Nieuszkodzony",
        "country_origin": "Polska",
        "vin": "zfacf7h38m6x10213",
    },
]
