name: Docker build and test

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
    
   steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker-compose build app
    - name: Run isort
      run: docker-compose run app poetry run isort . --check --profile=black
    - name: Run black
      run: docker-compose run app poetry run black . --check
    - name: Run tests
      run: docker-compose run app poetry run pytest
    - name: Stop docker container
      if: always()
      run: docker-compose down
