name: Docker build and test

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3
     - name: Run isort
       run:  poetry run isort . --check --profile=black
     - name: Run black
       run: poetry run black . --check
     - name: Run tests
       run: poetry run pytest tests/